# Server
quarkus.http.port=8344
# Jackson
quarkus.jackson.fail-on-unknown-properties=false

# Datasource Mysql
quarkus.datasource.db-kind=mysql
quarkus.datasource.jdbc.url=jdbc:mysql://localhost:3306/testMysql
quarkus.datasource.username=root
quarkus.datasource.password=admin

# Hibernate
quarkus.hibernate-orm.database.generation=update
quarkus.hibernate-orm.log.sql=true

quarkus.swagger-ui.path=swaggerui
quarkus.swagger-ui.always-include=true


