# Server
quarkus.http.port=8344
# Jackson
quarkus.jackson.fail-on-unknown-properties=false

# Datasource H2
quarkus.datasource.db-kind=h2
quarkus.datasource.jdbc.url=jdbc:h2:mem:customerDB;DB_CLOSE_DELAY=-1
quarkus.datasource.username=admin
quarkus.datasource.password=admin

# Hibernate
quarkus.hibernate-orm.database.generation=drop-and-create
quarkus.hibernate-orm.log.sql=true

# Consola H2
quarkus.h2.console.enabled=true
quarkus.h2.console.path=/h2


